[supervisord]
nodaemon=false
logfile=/root/data/projects/github.com/datacollector/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
pidfile=/root/data/projects/github.com/datacollector/supervisor/supervisord.pid
loglevel=info

[unix_http_server]
file=/root/data/projects/github.com/datacollector/supervisor/supervisor.sock

[supervisorctl]
serverurl=unix:///root/data/projects/github.com/datacollector/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /root/data/projects/github.com/datacollector/supervisor/programs/*.conf
