[program:datacollector]
command=/root/data/projects/github.com/datacollector/venv/bin/python3 api/server.py
directory=/root/data/projects/github.com/datacollector
user=root
autostart=true
autorestart=true
startretries=3
startsecs=3
stderr_logfile=/root/data/projects/github.com/datacollector/logs/flask.log
stdout_logfile=/root/data/projects/github.com/datacollector/logs/flask.log
environment=FLASK_HOST="127.0.0.1",FLASK_PORT="18180"
priority=20
