[program:postgresql]
command=/usr/bin/postgres -D /root/database/postgresql/
user=postgres
autostart=true
autorestart=true
startretries=3
stderr_logfile=/root/database/postgresql/logs/pg_supervisor.log
stdout_logfile=/root/database/postgresql/logs/pg_supervisor.log
priority=10
